@startuml
'https://plantuml.com/class-diagram

interface TransportConfig
class StdioTransportConfig
class StreamableHttpTransportConfig
class HttpTransportConfig
class SseTransportConfig

TransportConfig <|-- HttpTransportConfig
TransportConfig <|-- StdioTransportConfig
HttpTransportConfig <|-- StreamableHttpTransportConfig
HttpTransportConfig <|-- SseTransportConfig

@enduml