@startuml
'https://plantuml.com/class-diagram

interface Session
class InMemorySession
class JsonSession
class JedisSession
class MysqlSession
class RedissonSession

Session <|-- InMemorySession
Session <|-- JsonSession
Session <|-- JedisSession
Session <|-- MysqlSession
Session <|-- RedissonSession


@enduml