@startuml
'https://plantuml.com/class-diagram

interface StateModule
class ReActAgent
class Memory
class PlanNotebook
class StructuredOutputCapableAgent

StateModule <|-- ReActAgent
StateModule <|-- Memory
StateModule <|-- PlanNotebook
StateModule <|-- StructuredOutputCapableAgent

@enduml