@startuml
'https://plantuml.com/class-diagram

class ContentBlock
class TextBlock
class ToolUseBlock
class ToolResultBlock
class ThinkingBlock
class ImageBlock
class AudioBlock
class VideoBlock

ContentBlock <|-- TextBlock
ContentBlock <|-- ToolUseBlock
ContentBlock <|-- ToolResultBlock
ContentBlock <|-- ThinkingBlock
ContentBlock <|-- ImageBlock
ContentBlock <|-- AudioBlock
ContentBlock <|-- VideoBlock

@enduml